// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fiap.webapp.check2.hospital.Persistencias;

namespace fiap.webapp.check2.hospital.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20211030041538_BancoHospital")]
    partial class BancoHospital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.Doenca", b =>
                {
                    b.Property<int>("DoencaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("DoencaId");

                    b.ToTable("Doencas");
                });

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("EnderecoId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Capacidade")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("HospitalId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Hospitais");
                });

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime?>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PacienteId");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("HospitalId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.PacienteDoenca", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("DoencaId")
                        .HasColumnType("int");

                    b.HasKey("PacienteId", "DoencaId");

                    b.HasIndex("DoencaId");

                    b.ToTable("PacienteDoencas");
                });

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.Hospital", b =>
                {
                    b.HasOne("fiap.webapp.check2.hospital.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.Paciente", b =>
                {
                    b.HasOne("fiap.webapp.check2.hospital.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");

                    b.HasOne("fiap.webapp.check2.hospital.Models.Hospital", "Hospital")
                        .WithMany("Pacientes")
                        .HasForeignKey("HospitalId");

                    b.Navigation("Endereco");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.PacienteDoenca", b =>
                {
                    b.HasOne("fiap.webapp.check2.hospital.Models.Doenca", "Doenca")
                        .WithMany("PacientesDoencas")
                        .HasForeignKey("DoencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fiap.webapp.check2.hospital.Models.Paciente", "Paciente")
                        .WithMany("PacientesDoencas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doenca");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.Doenca", b =>
                {
                    b.Navigation("PacientesDoencas");
                });

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.Hospital", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("fiap.webapp.check2.hospital.Models.Paciente", b =>
                {
                    b.Navigation("PacientesDoencas");
                });
#pragma warning restore 612, 618
        }
    }
}
